main:
  - name: Aldeia
    url: /aldeia/
    weight: 10

  - name: Padel
    url: /padel/
    weight: 20

  - name: Runner
    url: /runner/
    weight: 30

  - name: Posts
    url: /blog/
    weight: 40



